# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: May Ho
title: PhD Research Student
email: mayho@neuro.mpg.de
website: https://github.com/mayho3

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: MayHo_
github_username:  mayho3
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cat_p3rson
linkedin_username: may-ho-neuro
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's May and I'm a PhD student currently studying inhibitory neuron development with Dr. Christian Mayer. I have extensive experience analyzing largue volumes of biological sequencing data.  Besides my PhD, I'm also passionte about user experience researcch and hope to apply the analytical and research skills
  I've gained to build user-friendly digital products. 

  I am most skilled in: <mark>Data Visualization</mark> and <mark>Quantitative Research</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CRISPR screen project
        link: github.com/mayho3
        # link_text: Project Website
       # additional_links:
         # - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
         #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Using CRISPR to screen important developmental gene technqiues
        description: | # this will include new lines to allow paragraphs
           The goal of the project is to examine how neuronal cell types are affected by the knockout of candidate developmental genes. Through the analysis and visualization of the biological data generated from sequencing the neurons,
           I hope to uncover genes and genetic programs that are critical for the development and specification of inhibitory neuron cell types.

           This project is a work-in-progres and a collaboration with a postdoc in my lab.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Max Planck Institute of Neurobiology
        link: neuro.mpg.de/mayer
        # link_text: boringcompany.com
        sub_title: PhD Research Student
        caption: September 2018 - Present
        quote: >
          “As long as our brain is a mystery, the universe, the reflection of the structure of the brain will also be a mystery.”― Santiago Ramón y Cajal
        description: | # this will include new lines to allow paragraphs
            I conduct research on the development of inhibitory neurons by applying statistical techniques like machine learning to analyze genomic data from neurons. I use programming languages such as R and Python for data wrangling and visualization. 


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IMPRS for Molecular Life Sciences
        caption: 2018 - Present
        sub_title: PhD Neurobiology
        quote: >
          The IMPRS for Molecular Life Sciences: From Biological Structures to Neural Circuits is a center of excellence for the training of PhD students in the areas of biochemistry, cell biology, molecular medicine, neurobiology and structural biology. 
        description: | # this will include new lines to allow paragraphs
          Through my graduate school, I've attended a number of workshops such as Data Visualization, Scientific Writing, and Graphic Design.

          I've also won 2nd Best Poster at our graduate school's bi-annual research seminar. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data visualization and user experience research, I'm interested in: 
      - Analoog photography
      - Piano 
      - Cinema
      - Art History

      Herzogstand

      ![Landscape](images/landscape.jpg "Landscape")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
